name: Build and deploy
on:
  push:
    branches:
      - develop
      - main
      - 'release/**'
      - 'hotfix/**'
      - newlzdev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'none'
        type: choice
        options:
        - none
        - dev
        - prodeast
      # environment:
      #   type: environment
jobs:
  dev:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Lint
        run: |
          echo "It is - DEVELOP"
  
  prod-dev:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - name: Lint
        run: |
          echo "DEV - env"
          echo "AWS_REGION - ${{ secrets.AWS_REGION }}"
          echo "My input env is - ${{ github.event.inputs.environment }}"

  prod-apac:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'prodeast' }}
    steps:
      - name: Lint
        run: |
          echo "PROD - env"
          echo "CLOUDFRONT_DISTRIBUTION_ID - ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          echo "My input env is - ${{ github.event.inputs.environment }}"